if (NOT __compile_definitions_INCLUDED)
  set (__compile_definitions_INCLUDED ON)

  string (TIMESTAMP BUILD_TIMESTAMP)
  target_compile_definitions (${PROJECT_NAME}
    PRIVATE
      PROJECT_DESCRIPTION="${PROJECT_DESCRIPTION}"
      BUILD_TIMESTAMP="${BUILD_TIMESTAMP}"
      VERSION="${PROJECT_VERSION}"
      VERSION_MAJOR=${PROJECT_VERSION_MAJOR}
      VERSION_MINOR=${PROJECT_VERSION_MINOR}
      VERSION_PATCH=${PROJECT_VERSION_PATCH}
  )

endif ()
